using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Timed_Math_Quiz
{
    public partial class Form1 : Form
    {
        public int timeLeft;
        public int a;
        public int b;
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            timeLeft = 4;
            timerLabel.Text = timeLeft.ToString();
            Random r = new Random();
            a = r.Next(12) + 1;
            b = r.Next(12) + 1;
            aLabel.Text = a.ToString();
            bLabel.Text = b.ToString();


            timer1.Start();


            startButton.Enabled = false;
            doneButton.Enabled = true;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            timer1.Enabled = true;
            timer1.Stop();
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            if (timeLeft > 0)
            {
                timeLeft--;
                timerLabel.Text = timeLeft.ToString();
            }
            if (timeLeft == 0)
            }
                doneButton.Enabled = false;
                startButton.Enabled = true;
                timer1.Stop();
                timerLabel.Text = "";

private void label1_Click(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {

        }

        private void button2_Click(object sender, EventArgs e)
        {

        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void label6_Click(object sender, EventArgs e)
        {

        }

        private void label1_Click_1(object sender, EventArgs e)
        {

        }

        private void label3_Click_1(object sender, EventArgs e)
        {

        }

        private void label1_Click_2(object sender, EventArgs e)
        {

        }

        private void label2_Click_1(object sender, EventArgs e)
        {

        }

        private void label1_Click_3(object sender, EventArgs e)
        {

        }
    }

    private void doneButton_Click(object sender, EventArgs e)
    {
        doneButton.Enabled = false;
        startButton.Enabled = true;
        timer1.Stop();

        int c = a + b;
        if (answerBox.Text = c.ToString())
        {
            timer1.Stop();
            timerLabel.Text = "You are the Best!";
        }
        else
        {
            timerLabel.Text = "Better Luck Next Time!";
        }


    }
}
}
